# Generated by Django 5.0.4 on 2024-08-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="login_expires_in",
            field=models.DateTimeField(null=True),
        ),
    ]
