# Generated by Django 4.2.11 on 2024-08-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserAuth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
