# Generated by Django 4.2.11 on 2024-08-01 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("time", models.DateField()),
                ("meterage", models.FloatField()),
                ("price", models.BigIntegerField()),
                ("price_per_meter", models.FloatField()),
                ("image", models.URLField()),
                ("description", models.TextField()),
                ("floor", models.IntegerField()),
                ("build_date", models.IntegerField()),
                ("rooms", models.IntegerField()),
                ("facilities", models.JSONField()),
                ("direction", models.CharField(max_length=255)),
                ("document_type", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("priorities", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="BuildingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.ImageField(upload_to="house_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ProximityFinder.building",
                    ),
                ),
            ],
        ),
    ]
