# Generated by Django 5.0.4 on 2024-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProximityFinder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="Prioritized",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
