# Generated by Django 5.0.4 on 2024-05-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProximityFinder", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="House",
            new_name="Building",
        ),
        migrations.RenameModel(
            old_name="HouseImage",
            new_name="BuildingImage",
        ),
    ]
