# Generated by Django 5.0.4 on 2024-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProximityFinder", "0002_comment_delete_buildingimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="sentiment",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
