# Generated by Django 5.0.4 on 2024-05-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProximityFinder", "0002_rename_house_building_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Area",
        ),
    ]
