# Generated by Django 5.0.4 on 2024-05-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProximityFinder", "0003_delete_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
