#this file should be at the same level with manage.py to run correctly.
import pandas as pd
import os
import django
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'CharKhone.settings')
django.setup()

from ProximityFinder.models import Building
from extentions import utils


homes = [
    {
        'id': 1,
        'city': 'زنجان',
        'title': 'برج فردوس شهرک رجایی',
        'category': 'فروش آپارتمان', 
        'time': '۱۱ ساعت پیش در زنجان', 
        'meterage': 84, 
        'price': 2190000000,
        'price_per_meter': 26071000, 
        'image': 'https://s100.divarcdn.com/static/photo/afra/post/C7HjehaDo92J-AdxDhmhOQ/ce42436a-1152-4e4f-9351-b9db13919b4e.jpg', 
        'description': 'رجایی ایثار هشت برج فردوس بادسترسی اسان به مرکز \nاسناسور دو لاین بزرگ\nنگهبانی 24ساعته ودوربین مدار بسته\nپارکنیگ در حیاط\nعکسا گویای همه چی درمورد واحد می باشد\nفروش فوری بصورت نقدی',
        'floor': 10, 
        'all_floors': 10, 
        'build_date': 1394, 
        'rooms': 2, 
        'latitude': 36.684268897818, 
        'longitude': 48.474297523499, 
        'elevator': 1, 
        'parking': 1, 
        'warehouse': 1, 
        'jahat': '', 
        'vahed': '6', 
        'sanad': 'تک‌برگ', 
        'status': 'بازسازی شده'    
    },
    {
        'id': 2,
        'city': 'زنجان',
        'title': 'فروش خانه در تمیز واقع در اسلام آباد',
        'category': 'فروش خانه و ویلا', 
        'time': '۱۱ ساعت پیش در زنجان', 
        'meterage': 45, 
        'price': 1150000000, 
        'price_per_meter': 25555000, 
        'image': 'https://s100.divarcdn.com/static/photo/afra/post/xI_Upanh3aj1w3IMrtAGMg/46a15c71-1128-4729-a0fc-5cd7a492c72f.jpg', 
        'description': 'فروش خانه ویلایی تر تمیز واقع در اسلام آباد بدون یک ریال خرج',
        'floor': '', 
        'all_floors': '', 
        'build_date': 1388, 
        'rooms': 1, 
        'latitude': 36.6887947, 
        'longitude': 48.4664734, 
        'elevator': 0, 
        'parking': 1, 
        'warehouse': 0, 
        'jahat': '', 
        'vahed': '', 
        'sanad': '', 
        'status': 'بازسازی نشده'    
    },
    {
        'id': 3,
        'city': 'زنجان',
        'title': 'آپارتمان اکباتان پونک',
        'category': 'فروش آپارتمان', 
        'time': '۱۰ ساعت پیش در زنجان', 
        'meterage': 90, 
        'price': 2280000000, 
        'price_per_meter': 25333000, 
        'image': 'https://s100.divarcdn.com/static/videos/thumbnails/4a2dfee7-1cd6-45bb-8ea8-46568dac2ff2.jpg', 
        'description': 'مجتمع اکباتان\nواحد فوق لوکس\nدارای کناف و پرده و کابینت لوکس\nپشت پمپ گاز گلشهر\nبازدید = یک ساعت قبل تماس بگیرید',
        'floor': 1, 
        'all_floors': 1, 
        'build_date': 1393, 
        'rooms': 2, 
        'latitude': 36.666400880147, 
        'longitude': 48.54171900743, 
        'elevator': 1, 
        'parking': 1, 
        'warehouse': 1, 
        'jahat': '', 
        'vahed': '', 
        'sanad': '', 
        'status': 'بازسازی نشده'    
    },
    {
    'id': 4,
    'city': 'زنجان',
    'title': 'آپارتمان ۷۴ متری جنوبی ساتراپ پونک',
    'category': 'فروش آپارتمان',
    'time': '۱۱ ساعت پیش در زنجان',
    'meterage': 74,
    'price': 2100000000,
    'price_per_meter': 28378000,
    'image': 'https://s100.divarcdn.com/static/photo/afra/post/DWJkMmNgxj8nAN1oamWMmQ/6885ed79-9b30-4b28-8523-c8f38d2e4861.jpg',
    'description': 'آپارتمان ۷۴ متری جنوبی ساتراپ کل ساختمان ۸ واحد هر طبقه ۲ واحد دارای آسانسور، پارکینگ حیاط قید شده در سند، انباری، آگهی دهنده مشاور املاک',
    'floor': 2,
    'all_floors': 4,
    'build_date': 1394,
    'rooms': 2,
    'latitude': 36.661159925322,
    'longitude': 48.552997659859,
    'elevator': 1,
    'parking': 1,
    'warehouse': 1,
    'jahat': 'جنوبی',
    'vahed': 2,
    'sanad': 'تک‌برگ',
    'status': 'بازسازی نشده'
    },
    {
    'id': 5,
    'city': 'زنجان',
    'title': 'خانه ویلایی فرودگاه تازه بازسازی شده فول',
    'category': 'فروش خانه و ویلا',
    'time': '۱۱ ساعت پیش در زنجان',
    'meterage': 80,
    'price': 2100000000,
    'price_per_meter': 23333000,
    'image': 'https://s100.divarcdn.com/static/videos/thumbnails/7ecbee33-5b42-4454-bad0-4a55161c8d49.jpg',
    'description': 'با سلام\nواحد فوق تمیز دوخوابه کف سرامیک تازه کابینت و دربهای همگی پی وی سی بروز و حیاط تازه موزائیک شده ودارای دوانباری تمیز مثل اپارتمان بروز \nواقع در کوچه شهید ابوالفضلی اول بن بست همه چیز تازه و بروز شده تیرآهن کمد دیواری \nفروش نقدی و یا معاوضه با امتیاز مسکن تا نصف قیمت یا علی \nباتشکراز دیوار',
    'floor': '',
    'all_floors': '',
    'build_date': 1386,
    'rooms': 2,
    'latitude': 36.675287698061,
    'longitude': 48.460329979753,
    'elevator': 0,
    'parking': 1,
    'warehouse': 1,
    'jahat': 'شمالی',
    'vahed': '',
    'sanad': 'قول نامه ای',
    'status': 'بازسازی شده'
    },
    {
    'id': 6,
    'city': 'زنجان',
    'title': 'آپارتمان 113 متر در اعتمادیه',
    'category': 'فروش آپارتمان',
    'time': '۱۱ ساعت پیش در زنجان',
    'meterage': 113,
    'price': 4859000000,
    'price_per_meter': 43000000,
    'image': 'https://s100.divarcdn.com/static/photo/afra/post/7ZgjItXqABWXpzCK1UiRNQ/210622c0-38da-48ef-9ea0-6d805c0dbc42.jpg',
    'description': 'کل مجتمع: 7 واحد \nآپارتمان : طبقه سوم شمالی\nنورگیری آپارتمان: عالی (از هر دوطرف نورگیری و چرخش هوا بسیار خوبی دارد)\nکوچه دنج (13 وسط) با تردد کم و نزدیک به پارک \nموتورخانه مرکزی (بدون نیاز به پکیج)\nسرویس بهداشتی و حمام لوکس\nکف سرامیک\nکابینت MDF \nاتاق خواب بزرگ \nانباری بزرگ',
    'floor': 2,
    'all_floors': 1,
    'build_date': 1386,
    'rooms': 1,
    'latitude': 36.639197184091,
    'longitude': 48.171323239803,
    'elevator': 0,
    'parking': 0,
    'warehouse': 0,
    'jahat': '',
    'vahed': '',
    'sanad': '',
    'status': ''
    },
    {
    'id': 7,
    'city': 'زنجان',
    'title': 'آپارتمان 90متری.مجتمع زیبای آفتاب',
    'category': 'فروش آپارتمان',
    'time': '۱۰ ساعت پیش در زنجان',
    'meterage': 90,
    'price': 2900000000,
    'price_per_meter': 3222000,
    'image': '',
    'description': 'مجتمع آفتاب واقع در اراضی پایین کوه (میثاق). بلوک کناری با ویوی فضای سبز. طبقه ۲. بازسازی شده و تمیز. امکان بازدید با هماهنگی قبلی. ((قابل معاوضه با واحد کوچکتریا اتومبیل بطوریکه ۱ میلیارد یا بیشتر سر بگیرم)) امکان رهن کامل تا ۵۰۰ میلیون.',
    'floor': 2,
    'all_floors': 4,
    'build_date': 1387,
    'rooms': 2,
    'latitude': 36.689409863683,
    'longitude': 48.523617063726,
    'elevator': 1,
    'parking': 1,
    'warehouse': 0,
    'jahat': '',
    'vahed': '',
    'sanad': 'تک‌برگ',
    'status': 'بازسازی شده'
    },
    {
    'id': 8,
    'city': 'زنجان',
    'title': 'آپارتمان ۹۶ متری شخصی ساز پونک',
    'category': 'فروش آپارتمان',
    'time': '۶ ساعت پیش در زنجان',
    'meterage': 96,
    'price': 3250000000,
    'price_per_meter': 33854000,
    'image': 'https://s100.divarcdn.com/static/photo/afra/post/dgiaLWQ87eCSj37lIUR93Q/b5253cf6-78c2-47a4-99c6-8227f2230f05.jpg',
    'description': '⚜️سازه کاملا شخصی ساز؛شیک وخوش نقشه\n⚜️یک واحد از ۶ واحد(این واحد طبقه آخر میباشد)\n⚜️کابینت ام دی اف؛کولر گازی وسقف رابیتس\n⚜️سالن بزرگ وقابل چی یدمان وتراس بزرگ\n⚜️پارکینگ قید در سند ودرب ریموت دار\n⚜️دسترسی عالی ونزدیکی به امکانات\n⚜️امکان بازدید برای خریدار واقعی با هما  اهنگی قبلی',
    'floor': 3,
    'all_floors': 3,
    'build_date':1399,
    'rooms': 2,
    'latitude': 36.664404899753,
    'longitude': 48.540890055193,
    'elevator': 1,
    'parking': 1,
    'warehouse': 0,
    'jahat': '' ,
    'vahed': '2' ,
    'sanad': 'تک برگ',
    'status': 'بازسازی نشده'
    },
    {
    'id': 9,
    'city': 'زنجان',
    'title': 'سعدی وسط با ۴۲۰ متر زیر بنا',
    'category': 'فروش خانه و ویلا',
    'time': '۶ ساعت پیش در زنجان',
    'meterage': 420,
    'price': 18000000000,
    'price_per_meter': 100000000,
    'image': 'https://s100.divarcdn.com/static/photo/afra/post/zWvhBVA6ov_YfrwK1aW-4w/a079cfb8-b087-4e3c-b024-387c11211271.jpg',
    'description': 'خانه ویلایی با ۴۲۰ متر زیر بنا در سه طبقه مجزا واقع در بهترین منطقه سعدی وسط و نزدیک به خیابان اصلی سعدی وسط، قیمت زمین در این موقعیت متری ۱۰۰ م است و مناسب برای مسکونی و مطب پزشک و دندان پزشکی و فیوز تراپی .و جای آسانسور برای نصب در نظر گرفته شده است.',
    'floor': 4,
    'all_floors': 1,
    'build_date': 1380,
    'rooms': 1,
    'latitude': 36.670313530129,
    'longitude': 48.483839463991,
    'elevator': 1,
    'parking': 1,
    'warehouse': 1,
    'jahat': 'شمالی',
    'vahed': '',
    'sanad': 'تک‌برگ',
    'status': 'بازسازی نشده'
    },
    {
    'id': 10,
    'city': 'زنجان',
    'title': 'زمین مسکونی در خیابان امام خمینی رازبین',
    'category': 'فروش زمین و کلنگی',
    'time': '۶ ساعت پیش در زنجان',
    'meterage': 400,
    'price': 3000000000,
    'price_per_meter': 135700000,
    'image': 'https://s100.divarcdn.com/static/photo/afra/post/Uvwh-YLTwXTQpZmV4lfF7w/7cae4cf4-3bc7-46b1-a717-1b018420b073.jpg',
    'description': 'به نام خدا \n⚜️املاکـ یوسفی(رازبین)⚜️\n_____________________________________\n♻️همان چیزی که در ذهن شماستـ♻️\n♻️ما به جای شما منطقه را گشته ایمـ\n♻️بهترین فایلها را برای شما در نظر گرفته ایم\u200dـ\n__________________________________________\n__________________________________________\n✅مشخصات:\n⬅️ زمین(400)متری\n⬅️داخل با افت(محدوده)\n⬅️خیابان اصلی(خیابان امام خمینی)\n⬅️مدارک موجود\n__________________________________________\n✅قابلیت وام از بنیاد مسکن\n\n__________________________________________\n♦️دارای مجوز رسمی از اتحادیه املاک\n♦️اخذ کدرهگیری از سامانه املاک\n♦️خرید فروش از شما تضمین سود از ما\n__________________________________________',
    'floor': '',
    'all_floors': '',
    'build_date': 1370,
    'rooms': 1,
    'latitude': 36.625427,
    'longitude': 48.409084,
    'elevator': 0,
    'parking': 0,
    'warehouse': 0,
    'jahat': '',
    'vahed': '',
    'sanad': '',
    'status': ''
    },
    {
    'id': 11,
    'city': 'زنجان',
    'title': 'خانه ویلایی در خیابان فردوسی',
    'category': 'فروش خانه و ویلا',
    'time': '۸ ساعت پیش در زنجان',
    'meterage': 90,
    'price': 2000000000,
    'price_per_meter': 19047000,
    'image': '',
    'description': 'خانه بسیار تمیز دارای کابینت ام دی اف اجاق گاز رو میزی و هود ، کاغذ دیواری  ، دارای ۳تا انباری و حیاط ۲۵متری یک اتاق خواب ۱۵متری و پذیرایی با پنجره بزرگ به سمت حیاط \nبن بست ۴ متری دارد \nخانه بسیار تمیز و شیک می‌باشد \nبرای بازدید تماس بگیرید \n****و‌***** ****و‌********* ***** یک *********',
    'floor': 1,
    'all_floors': 0,
    'build_date': 1390,
    'rooms': 1,
    'latitude': 36.003562528951,
    'longitude': 48.353576660156,
    'elevator': 1,
    'parking': 1,
    'warehouse': 0,
    'jahat': 'شمالی',
    'vahed': '',
    'sanad': 'تک‌برگ',
    'status': 'بازسازی شده'
    },
    {
    'id': 12,
    'city': 'زنجان',
    'title': 'آپارتمان نقلی علوم پایه',
    'category': 'فروش آپارتمان',
    'time': '۸ ساعت پیش در زنجان',
    'meterage': 50,
    'price': 1670000000,
    'price_per_meter': 33400000,
    'image': 'https://s100.divarcdn.com/static/photo/afra/post/gIOfO0F7NboX_xb99Y981Q/7143c52c-4a8a-47da-9f46-eb7a77e9917b.jpg',
    'description': 'آپارتمان مذکورواقع در بهترین و امنترین منطقه ی ویلا نشین. تخفیف گذاشتم.\nمنطقه رو درنظر داشته باشد\nباکمی تغییر شبیه لوکسترین آپارتمان های تهران خواهد شد\n\nسند تک برگ و قابل انتقال✨️\nبا همسایگان محترم.✨️\nدسترسی به تمام نقاط.\nانشعابات جدا\nتک خواب نقلی و شیک.\nبهترین سرمایه گذاری.✨️\nمسکونی و امتیاز تجاری.✨️\nوام مسکن اخذ نمی شود.\nقابلیت رهن ۳۰۰ میلیونی.✨️\nهر طبقه یک واحد.✨️\nکل ساختمان ۴ طبقه و ۴ واحد هست.\nیک از چ چهار. بالای همکف.\nگرمایش: بخاری و آبگرمکن\n\nبا کمترین هزینه صاحب آپارتمان علوم پایه باشید',
    'floor': 1,
    'all_floors': 4,
    'build_date': 1398,
    'rooms': 1,
    'latitude': 36.688080319972,
    'longitude': 48.498447102777,
    'elevator': 0,
    'parking': 0,
    'warehouse': 0,
    'jahat': '',
    'vahed': '',
    'sanad': '',
    'status': 'بازسازی نشده'
    },
    {
    'id': 13,
    'city': 'زنجان',
    'title': 'آپارتمان مرکز شهر دوخواب شخصی ساز',
    'category': 'فروش آپارتمان',
    'time': '۹ ساعت پیش در زنجان',
    'meterage': 62,
    'price': 1900000000,
    'price_per_meter': 30645000,
    'image': '',
    'description': 'یک واحد آپارتمان',
    'floor': 4,
    'all_floors': 5,
    'build_date': 1392,
    'rooms': 2,
    'latitude': 36.68388814902,
    'longitude': 48.475153972978,
    'elevator': 1,
    'parking': 1,
    'warehouse': 0,
    'jahat': '',
    'vahed': '',
    'sanad': '',
    'status': 'بازسازی نشده',
    },
    {
    'id': 14,
    'city': 'زنجان',
    'title': 'منزل ویلایی در اسلام اباد',
    'category': 'فروش خانه و ویلا',
    'time': '۶ ساعت پیش در زنجان',
    'meterage': 155,
    'price': 3500000000,
    'price_per_meter': 2800000000,
    'image': '',
    'description': 'یک باب منزل مسکونی واقع در اسلام اباد خیابان شهید اصفهانی کوچه شهید حسین محمدی \nیک زیر زمین قابل سکونت و یک واحد مجزا\nبا دو درب ورودی\nعرصه و اعیان ۱۲۵ متر\nزیربنای دو واحد حدودا ۱۵۵ متر\nبا حیاط بزرگ\nسند به صورت تک برگ\nهر دو واحد قابل سکونت و در حال حاضر داری مستاجر میباشند.\nدر صورت تمایل برای معامله با شماره تماس *********** تماس حاصل بفرمایید.',
    'floor': 0,
    'all_floors': 1,
    'build_date': 1377,
    'rooms': 3,
    'latitude': 36.685602129184,
    'longitude': 48.471324294806,
    'elevator': 1,
    'parking': 1,
    'warehouse': 0,
    'jahat': '',
    'vahed': '',
    'sanad': 'سند به صورت تک برگ',
    'status': 'بازسازی نشده',
    },
    {
    'id': 15,
    'city': 'زنجان',
    'title': 'سالن باغ 700متر فرصت سرمایه گذاری',
    'category': 'فروش خانه و ویلا',
    'time': '۴ ساعت پیش در زنجان',
    'meterage': 300,
    'price': 2200000000,
    'price_per_meter': 3142000,
    'image': 'https://s100.divarcdn.com/static/photo/afra/post/oJ2JkSzavrxsZ1UnCO919g/d5fa0a6c-8682-4b05-b8ae-322a88166f30.jpg',
    'description': 'دونبش میباشد هم از خیابان هم کوچه .کلا 700متر زیر بنا دارد که 250متر سالن الباقی حیاط و انباری نگهبانی نیمه ساخت  از میدان بسیج کلا 13دقع راهشه اسفالت تا دم باغ اومده  دور بر هم  همه کلا باغ ویلا  جای با امنیت خیلی خیلی بالا  بهترین بازدهی برای سرمایه گذاری. پیشرفت دوبرابریه قیمت رو هر سال داره محدوده کلا داره شهرک سازی میشه انفجاری قیمت ها هرسال میره بالا من ولی همون قیمت قبل سال گذاشتم .بهترین مکان برای تولیدی ها  پرورشی ها هم سالن بزرگ داره هم حیاط بزرگ .اب و برق هم هست .درمحدوده قرار گرفته .که میتونید یه کسب کار راه بندازین هم واسه ملک وهم واسه کسب و کار وام بگیرین چون نگرفتیم هنوز  .تعویض هم داریم ملک و خودرو .نقد و اقساط .بهترین مکان برای سرمایه گذاری امن ملک هیچ موقع ضرر نمیاره اینجا هم که شرایطشو گفتم  ممنون .نوری',
    'floor': 1,
    'all_floors': 1,
    'build_date': 1400,
    'rooms': 3,
    'latitude': 36.570338260676,
    'longitude': 48.72824005619,
    'elevator': 0,
    'parking': 0,
    'warehouse': 0,
    'jahat': 'شمالی',
    'vahed': '',
    'sanad': '',
    'status': 'بازسازی نشده'
    },
    {
    'id': 16,
    'city': 'زنجان',
    'title': 'فروش اپارتمان ۱۸۵ متری کوچمشکی شمالی',
    'category': 'فروش آپارتمان',
    'time': '۴ ساعت پیش در زنجان',
    'meterage': 185,
    'price': 11100000000,
    'price_per_meter': 60000000,
    'image': '',
    'description': 'فروش یکباب اپارتمان خشک درقسمت شمالی کوچمشکی بابهترین مصالح  ونقشه .\nبا احترام لطفا املاکی ها تماس نگیرند.باتشکر از عوامل محترم دیوار',
    'floor': 1,
    'all_floors': 4,
    'build_date': 1402,
    'rooms': 3,
    'latitude': 36.684284116539,
    'longitude': 48.496105943709,
    'elevator': 1,
    'parking': 0,
    'warehouse': 1,
    'jahat': 'شمالی',
    'vahed': '',
    'sanad': 'تک‌برگ',
    'status': 'بازسازی شده'
    },
    {
    'id': 17,
    'city': 'زنجان',
    'title': 'فروش ویلایی ۴۵۰ متری ویلایی',
    'category': 'فروش خانه و ویلا',
    'time': '۳ ساعت پیش در زنجان',
    'meterage': 300,
    'price': 28500000000,
    'price_per_meter': 63333000,
    'image': '',
    'description': 'فروش دوواحد ساختمان چسبیده به هم هرکدام ۲۲۵ مترمربع.جمع ۴۵۰ متر .\nبا احترام لطفا املاکی ها تماس نگیرند.\nباتشکر از عوامل محترم دیوار',
    'floor': 1,
    'all_floors': 4,
    'build_date': 1381,
    'rooms': 4,
    'latitude': 36.681859542966,
    'longitude': 48.498104014336,
    'elevator': 1,
    'parking': 0,
    'warehouse': 0,
    'jahat': 'شمالی',
    'vahed': '',
    'sanad': 'تک برگ',
    'status': 'بازسازی شده'
    },
    {
    'id': 18,
    'city': 'زنجان',
    'title': 'آپارتمان مسکونی m6 گلشهر، طبقه۴ ، شمالی و دارای حیاط',
    'category': 'فروش آپارتمان',
    'time': '۳ ساعت پیش در زنجان',
    'meterage': 89,
    'price': 2000000000,
    'price_per_meter': 22471000,
    'image': '',
    'description': '۸۹ متر ،پارکینگ ریموت دار، انباری، شمالی و دارای حیاط، خشک ، وام ۵۵۰ با اقساط ۶ میلیونی، نورگیری عالی، بهترین پروژه مسکن ملی',
    'floor': 1,
    'all_floors': 2,
    'build_date': 1403,
    'rooms': 1,
    'latitude': 36.658936084045,
    'longitude': 48.586157352747,
    'elevator': 1,
    'parking': 0,
    'warehouse': 0,
    'jahat': '',
    'vahed': '',
    'sanad': '',
    'status': 'بازسازی نشده'
    },
    {
    'id': 19,
    'city': 'زنجان',
    'title': 'آزادگان توحید غربی',
    'category': 'فروش آپارتمان',
    'time': '۳ ساعت پیش در زنجان',
    'meterage': 91,
    'price': 4000000000,
    'price_per_meter': 42000000,
    'image': 'https://s100.divarcdn.com/static/photo/afra/post/8h3K6SNIVGOTTHenmwpevw/0e017666-4a93-44ac-a0c9-e9e7c181b11f.jpg',
    'description': 'فوری فروشی\nآزادگان، توحید غربی',
    'floor': 1,
    'all_floors': 2,
    'build_date': 1390,
    'rooms': 2,
    'latitude': 36.696232069257,
    'longitude': 48.499809098117,
    'elevator': 1,
    'parking': 0,
    'warehouse': 0,
    'jahat': '',
    'vahed': '',
    'sanad': '',
    'status': 'بازسازی نشده'
    },
    {
        'id': 20, 
        'city': 'زنجان', 
        'title': '۶۷متر شهرک رجایی', 
        'category': 'فروش آپارتمان', 
        'time': '۱ ساعت پیش در زنجان', 
        'meterage': 67, 
        'price': 1950000000, 
        'price_per_meter': 29104000, 
        'image': 'https://s100.divarcdn.com/static/photo/afra/post/IvPaZZtHqMdh6AAKlPvYjg/9fb3b468-30f9-47c5-99d7-d5a30c771207.jpg', 
        'description': 'بهترین موقعیت برای سرمایه گذاری:\n\n✅واحد شخصی ساز\n✅۶۷متر تک خواب \n✅پارکینگ اختصاصی\n✅آسانسور\n✅انباری \n✅انشعابات مجزا\n ✅در بهترین لوکیشن شهرک\n✅۲۵۰میلیون رهن کامل ک از مبلغ کل کسر میشود.\n\nسند آزاد آماده ی اخذ وام میباشد.', 'floor': '۱', 'all_floors': '۴', 
        'build_date': 1396, 
        'rooms': 1, 
        'latitude': 36.683956968201, 
        'longitude': 48.473987780018, 
        'elevator': 1, 
        'parking': 1, 
        'warehouse': 1, 
        'jahat': '', 
        'vahed': '', 
        'sanad': '', 
        'status': ''
    },
    {   
        'id': 21, 
        'city': 'زنجان', 
        'title': 'آپارتمان ۹۲ متری اعتمادیه جنوبی ۶ واحده', 
        'category': 'فروش آپارتمان', 
        'time': '۱ ساعت پیش در زنجان', 
        'meterage': 92, 
        'price': 3000000000, 
        'price_per_meter': 32608000, 
        'image': '', 
        'description': 'واحد بسیار تمیز و با همسایگان محترم', 
        'floor': 2, 
        'all_floors': 3, 
        'build_date': 1388, 
        'rooms': 2, 
        'latitude': 36.639197234091,
        'longitude': 48.171325239803,
        'elevator': 0, 
        'parking': 1, 
        'warehouse': 1, 
        'jahat': '', 
        'vahed': '', 
        'sanad': '', 
        'status': ''
    },
    {
        'id': 22,
        'city': 'زنجان', 
        'title': 'آپارتمان سعدی وسط', 
        'category': 'فروش آپارتمان', 
        'time': '۸ ساعت پیش در زنجان', 
        'meterage': '۱۳۴', 
        'price': '۴٬۷۰۰٬۰۰۰٬۰۰۰', 
        'price_per_meter': '۳۵٬۰۷۴٬۰۰۰', 
        'image': '', 
        'description': 'فول امکانات تازه کاغذ دیواری شده کابینت تازه نصب شده سند آزاد', 
        'floor': '۴', 
        'all_floors': '', 
        'build_date': '۱۴۰۱', 
        'rooms': '۲', 
        'latitude': 36.693311043624, 
        'longitude': 48.549310729201, 
        'elevator': '1', 
        'parking': '1', 
        'warehouse': '1', 
        'jahat': '', 
        'vahed': '', 
        'sanad': '', 
        'status': ''
    },
    {'id': 23, 'city': 'زنجان', 'title': 'آپارتمان ۹۷ متری/شهرک نگین/برج نگبن', 'category': 'فروش آپارتمان', 'time': '۳ ساعت پیش در زنجان', 'meterage': '۹۷', 'price': '۳٬۷۸۳٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۹٬۰۰۰٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/afra/post/JxKzFqgZyuldxJd-XNxirA/aab8f7a8-d5c6-4b4a-832b-9a712bb9a06c.jpg', 'description': 'ادرس ملک حضوری تقدیم میگردد\n…………………………………………………………………………\nاگر قصد خرید یا فروش ملکی را دارید میتوانید با اعتماد و اطلاع از رزومه ی کاری ما در حفظ و ارتقا ملک خود اطمینان حاصل فرمایید\n\n⚜️متراژ: ۹۷\n⚜️تعداداتاق: ۲\n⚜️سال ساخت:  : ۱۴۰۱\n⚜️طبقه: اول(۹۷متر) و چهارم(۱۰۰متر) موجود میباشد\n⚜️اسانسور: دارد\n⚜️پارکینگ: دارد(مسقف و اختصاصی)\n⚜️انباری:     دارد\n⚜️سایرامکانات:واحدها بصورت تجهیز کامل،بسیار لوکس میباشند\n**سند تک برگ،آماده انتقال**\n**فروشندگان واقعی**\n\nnمشارکت در ساخت با رزومه قوی\n\nاملاک آتی:کوی نارون ، خیابان نارون اصلی رو به روی مدرسه نمونه بسیج', 'floor': '۱', 'all_floors': '', 'build_date': '۱۴۰۱', 'rooms': '۲', 'latitude': 36.687862, 'longitude': 48.529385, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 24, 'city': 'زنجان', 'title': 'آپارتمان ۱۰۰متری مجتمع صدف', 'category': 'فروش آپارتمان', 'time': 'یک ربع پیش در زنجان', 'meterage': '۱۰۰', 'price': '۲٬۴۵۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۲۴٬۵۰۰٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/neda/post/aA4HFaxHROfNuVve_J1mTQ/4647fa0d-09d0-48a2-8848-36e13b573ba7.jpg', 'description': 'باسلام اتوبان ۲۲بهمن بعدمسجدثارلله مجتمع صدف بلوک ۵واحد۴دوکله غرق درنورخواب هابزرگ تازه بازسازی شده کف سرامیک پنجره هاکلادوجداره بهترین جنس بازار.تازه نقاشی شده سرویس هاوآشپزخانه  کاشی تاسقف سرویس هابزرگ . بالکن بزرگ که پنجره نصب شده سندآزادآماده انتقال وگرفتن وام بلوک درورودی مجتمع واقع شده بهترین جای مجتمع خلاصه بدون ریالی خرج معاوضه باواحدبزرگتر والباقی نقداپرداخت میشه ممنون ازسایت خوب دیوار', 'floor': '۲', 'all_floors': '', 'build_date': '۱۳۸۳', 'rooms': '۲', 'latitude': 36.681830246836, 'longitude': 48.51198741449, 'elevator': '0', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 25, 'city': 'زنجان', 'title': 'فروش آپارتمان در پونک', 'category': 'فروش آپارتمان', 'time': '۹ ساعت پیش در زنجان', 'meterage': '۷۸', 'price': '۲٬۰۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۲۵٬۶۴۱٬۰۰۰', 'image': '', 'description': 'آپارتمان هاتف \nدوخواب \nطبقه ۵ \nباامکانات کامل \n۷۸متر \nباپارکینگ وانباری آسانسور میباشد \nسند آزاد', 'floor': '۲', 'all_floors': '', 'build_date': '۱۳۹۲', 'rooms': '۲', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 26, 'city': 'زنجان', 'title': 'پونک.مجتمع زیبای فراز.87 متر.دوخواب', 'category': 'فروش آپارتمان', 'time': '۱۲ ساعت پیش در زنجان', 'meterage': '۸۷', 'price': '۳٬۲۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۶٬۷۸۱٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/neda/post/bM6L-KxRSXi-n0bK2VLkQw/8c55971c-01eb-402a-8fb0-6cdc80e52604.jpg', 'description': 'با سلام\nواحد87 متری\nدوخواب\nتازه ساخت\nپکیج\nکابینتmdf\nآسانسور\nشوتینگ زباله\nپارکینگ', 'floor': '۲', 'all_floors': '۱۲', 'build_date': '۱۴۰۲', 'rooms': '۲', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 27, 'city': 'زنجان', 'title': 'اپارتمان ۷۰ متر', 'category': 'فروش آپارتمان', 'time': '۱۲ ساعت پیش در زنجان', 'meterage': '۷۰', 'price': '۳٬۲۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۴۵٬۷۱۴٬۰۰۰', 'image': '', 'description': 'اپارتمان ۷۰ متر پشت پاساژ هشت  بهشت ساختمان سعدی بلوک ۲ طبقه ۶', 'floor': '۵', 'all_floors': '', 'build_date': '۱۳۸۵', 'rooms': '۲', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 28, 'city': 'زنجان', 'title': 'آپارتمان۹۲متری اعتمادیه جنوبی۶واحده', 'category': 'فروش آپارتمان', 'time': '۱۱ ساعت پیش در زنجان', 'meterage': '۹۲', 'price': '۲٬۸۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۰٬۴۳۴٬۰۰۰', 'image': '', 'description': 'واحد بسیار تمیز و با همسایگان محترم\nفروش فوری مقطوع', 'floor': '۲', 'all_floors': '۳', 'build_date': '۱۳۸۸', 'rooms': '۲', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '0', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 29, 'city': 'زنجان', 'title': '۲واحد آپارتمان شخصی ساز قابل معاوضه', 'category': 'فروش آپارتمان', 'time': '۱۲ ساعت پیش در زنجان', 'meterage': '۲۰۰', 'price': '۱۰٬۰۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۵۰٬۰۰۰٬۰۰۰', 'image': '', 'description': '۲ واحد آپارتمان شخصی ساز در فاز ۴ گلشهر که با ۲ واحد ویلایی معاوضه می شود\n مشخصات آپارتمان ها به شرح ذیل می باشد\n۱_ یک واحد جنوبی ۳ خواب ( ۳ طبقه واحد دوم)\n۲_ یک واحد شمالی ۲ خواب ( ۴ طبقه واحد سوم)\n۳_هر دو دارای آسانسور می باشند\nشماره تماس صفر نهصدو نوزده ششصدو هفتادو چهار سی  و نه هفتادو دو', 'floor': '۲', 'all_floors': '۳', 'build_date': '۱۴۰۰', 'rooms': '+۴', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 30, 'city': 'زنجان', 'title': 'آپارتمان ۱۲متری خشک', 'category': 'فروش آپارتمان', 'time': '۱۴ ساعت پیش در زنجان', 'meterage': '۱۲۰', 'price': '۴٬۱۵۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۴٬۵۸۳٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/afra/post/OpfULeTYbI2viKgHbSgnGg/26795B78-22ED-4A67-851F-38334CFF2867.jpg', 'description': 'خ ۱۸متری احدی ۱۳ روبروی فضای سبز\n۴طبقه هرطبقه ۱واحد \nواحد دوم موجود\nپارکینگ و انباری و آسانسور\n۱۲۰متر مفید\n۳خواب\nدارای مطبخ و حمام مستر\nمتریال مورد استفاده بسیار بهتر از عرف منطقه می باشد.\n۱۰درصد بابت سند کسر می شود/.', 'floor': '۲', 'all_floors': '۴', 'build_date': '۱۴۰۳', 'rooms': '۳', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 31, 'city': 'زنجان', 'title': 'سعدی شمالی کوچه فروردین ۱۳۶مترجنوبی', 'category': 'فروش آپارتمان', 'time': '۱۴ ساعت پیش در زنجان', 'meterage': '۱۳۶', 'price': '۵٬۸۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۴۲٬۶۴۷٬۰۰۰', 'image': '', 'description': 'واحدبسیارمهندسی سازخوش نقشه نورگیرلووکس عاالی..کاملاتمیزوبازسازی شده..فروش فقط نقدی', 'floor': '۵', 'all_floors': '۵', 'build_date': '۱۳۹۱', 'rooms': '۲', 'latitude': 36.66578, 'longitude': 48.503883, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 32, 'city': 'زنجان', 'title': 'فروش آپارتمان جنوبی شهرک کارمندان', 'category': 'فروش آپارتمان', 'time': '۱۴ ساعت پیش در زنجان', 'meterage': '۱۶۴', 'price': '۱۰٬۵۵۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۶۴٬۳۲۹٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/afra/post/kmSL-WaZRmceHjt3oXo5Yw/0ac73a4c-a4e3-4f09-8035-94d1a236caab.jpg', 'description': 'سلام وقت بخیر \n    موقعیت جنوبی \nتجهیز و بازسازی شده با بهترین متریال \nلوکس \n      نورگیر \nخوش نقشه و خوش چیدمان \n     مخصوص سخت پسندان \nنزدیک خیابان اصلی \n        فایل های مشابه موجوده \nجهت بازدید به املاک نگین واقع در شهرک کارمندان فاز دوم خیابان دهم فرعی دوم از سمت مهدوی مراجعه فرمایید.\nمشاور شما افشین راد.', 'floor': '۲', 'all_floors': '۵', 'build_date': '۱۳۹۵', 'rooms': '۳', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''}   ,
    {'id': 33, 'city': 'زنجان', 'title': 'اعتمادیه ۱۰۱ متر', 'category': 'فروش آپارتمان', 'time': '۱۵ ساعت پیش در زنجان', 'meterage': '۱۰۱', 'price': '۴٬۷۵۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۴۷٬۰۲۹٬۰۰۰', 'image': '', 'description': 'آپارتمان \nاعتمادیه \n۱۰۱ متر\nشمالی\nطبقه ۳ از ۴\nخوش نقشه بدون پرتی\nفول تجهیز\nشیک\nکوچه دنج\nتخلیه', 'floor': '۳', 'all_floors': '۴', 'build_date': '۱۳۹۷', 'rooms': '۲', 'latitude': 36.669730781445, 'longitude': 48.499069066268, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 34, 'city': 'زنجان', 'title': 'اپارتمان قصرفردوس', 'category': 'فروش آپارتمان', 'time': '۱۳ ساعت پیش در زنجان', 'meterage': '۸۲', 'price': '۲٬۴۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۲۹٬۲۶۸٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/neda/post/Yoh_F9ArjEwRQgu_GtqysQ/5491af2b-4633-49e5-b131-69d76aafaa2e.jpg', 'description': 'پرده سلطنتی \nکف موکت \nپیکج\nکمد دیواری بزرگ\nدارای ۲ لاین آسانسور نفر بر و بار بر \nسند تک برگ  ازاد عرصه اعیان و با قابلیت اخذ وام نیز میباشد.', 'floor': '۱', 'all_floors': '', 'build_date': '۱۳۹۶', 'rooms': '۲', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 35, 'city': 'زنجان', 'title': 'پنت هوس 125 متری دوکله گلشهر', 'category': 'فروش آپارتمان', 'time': '۱۵ ساعت پیش در زنجان', 'meterage': '۱۲۵', 'price': '۴٬۳۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۴٬۴۰۰٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/videos/thumbnails/28ed003e-7fe9-4f94-8f2c-e6e62c91f7ed.jpg', 'description': '⚜️به نام یگانه معمارهستی⚜️\n\n✅️مشاورشما:محمد متین نو  وری هستم املاک آرژانتین\n\n✅️گلشهرفاز۳\n\n✔️مشخصات ملک:\n\n⚜️۱۱۰ متر بنا به همراه ۵۰ متر حیاط\n⚜️۲ خواب بزرگ و نورگیر\n⚜️واحد خ    خشک و کلید نخورده\n⚜️طبقه چهارم\n⚜️آسانسور\n⚜️پارکینگ و انباری اختصاصی\n⚜️ساختمان دوکله\n⚜️سقف کلا کناف با نورمخفی\n⚜️آشپزخانه د     دلباز و نورگیر به همراه مطبخ\n⚜️حمام مستر\n⚜️خوش نقشه\n⚜️فقط یک واحد به فروش میرسد\n⚜️فوری\n\n⚠️۴۰۰برای تحویل سند نگه میداریم\n\    \n❌❌واحد کلید نخورده می باشد❌❌️\n\n\n❌⚠️ فروش فقط نقدی معاوضه ندارن⚠️❌\n\n\n✴️همین امروز واحدتو میتونی تحویل بگیری✴️\n\n\n    n\n  ✅️⚜️فایل های مناسب با بودجه شما️⚜️✅\n  \n  ✴️مشارکت در ساخت با سازنده های معتبر✴️\n        ✔️✴️مشاور:محمد متین نوری✴️✔️\n         n \nآدرس املاکمون: جاوید کوچه اسماعیلی (روبروی انبار غله) جنب دفترخانه اسناد رسمی ۴۴', 'floor': '۴', 'all_floors': '۴', 'build_date': '۱۴۰۳', 'rooms': '۲', 'latitude': 36.66646, 'longitude': 48.550804, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 36, 'city': 'زنجان', 'title': 'فروش آپارتمان احرار فردوس ۸۰ متر', 'category': 'فروش آپارتمان', 'time': '۱۵ ساعت پیش در زنجان', 'meterage': '۸۰', 'price': '۲٬۰۵۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۲۵٬۶۲۵٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/neda/post/5oEJbiVU8ZHQIDwVn4OCoQ/7b658980-491a-4557-9ea4-4ad015c88a73.jpg', 'description': 'آپارتمان احرار فردوس دوخواب ۸۰ متر\nکف سرامیک؛کابینت ام دی اف؛طبقه سوم-واحد جنوبی - ویو ابدی و روبه اتوبان\nپارکینگ در سند محوطه می باشد', 'floor': '۳', 'all_floors': '', 'build_date': '۱۳۹۵', 'rooms': '۲', 'latitude': 36.659941572632, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 37, 'city': 'زنجان', 'title': 'آپارتمان ۱۵۵ متری کارمندان', 'category': 'فروش آپارتمان', 'time': '۱۵ ساعت پیش در زنجان', 'meterage': '۱۵۰', 'price': '۱۱٬۴۵۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۷۶٬۳۳۳٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/neda/post/xce8zsFlVz0u6kILeJK4Kw/a5b2b81b-1370-4e7a-9047-844a5d02529d.jpg', 'description': 'یک واحد آپارتمانی واقع در کارمندان به فروش می\u200cرسد \nمالک فروشنده و معامله\u200cگر \nپلان مهندسی بدون نقص \n☀️با نقشه س*** لاکچری \n✨آشپزخانه وسیع مختص به ککدبانو\n⭕لوکیشن اعیانی منطقه در خیابان ⭕های عریض کارمندان \n⭕معماری خیره کننده \n⭕ساخت بر اساس فنگ شویی \n✨دقت در طراحی و مهارت در اجرا \n⭐سازنده آرشیتکت به نام آشنا\nپارکینگ اختصاصی و سندی \n⭕نما باطراحی بسیار عالی \n⭕بهترین ویو \n⭕کارشناس فروش محمد امین \n⭕تخصص ما تضمین آرامش شماست ❤️ \nrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr\nلطفاً جهت آگاهی و کسب اطلاعات بیشتر ر به املاک اساتید مراجعه فرمایید  برای مشاهده فایل\u200cهای مشابه و متناوب', 'floor': '۴', 'all_floors': '', 'build_date': '۱۴۰۲', 'rooms': '۳', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 38, 'city': 'زنجان', 'title': 'آپارتمان ۱۳۳ متر/خ امام/نورگیر/لوکس/نوساز', 'category': 'فروش آپارتمان', 'time': '۱۵ ساعت پیش در زنجان', 'meterage': '۱۳۳', 'price': '۵٬۰۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۷٬۵۹۳٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/afra/post/EvuMwtk2TKV7ILvvgJsIFg/e26c60e6-e9c4-4ec2-a900-7fc4347c3455.jpg', 'description': '❗موقعیت عالی (تخفیف جزئی پای معامله)❗\n\n✅ واحد ۱۳۳ متر می\u200cباشد\n\n✅ نورگیری واحد مطابق عکس بسیار عالی \n\n✅ هر طبقه دو واحد\n\n✅ سال ساخت ۱۴۰۳\n\n✅ دارای پارکینگ، انباری و آسانسور\n\n✅ کف بصورت سرامیک\n\n✅ گرمایش بصورت پکیج \n\n✅ واحد نورپردازی شده و دارای پرده\n\n⚡مطابق عکس درحال حاضر استفاده دفتری دارد⚡\n---------------------------------------------------\n⚜️مشاور املاک محمدی⚜️\ \n⚜️ارائه بهترین مشاوره در زمینه خرید و فروش بصورت ❗رایگان❗\n⚜️امکان فعالیت در زمینه های مشارکت در ساخت، ساخت و ساز ، مزایده و و... \n⚜️ فروش مورد معامله شما بصورت فوری\n⚜️ یافتن فایل مورد مناسب شما کمتر از ۲۴ ساعت \n✅ ساعات پاسخگویی همه روزه ۹ الی ۲۱\n\ \nآدرس: خیابان شهدا، نبش کوچه شهدا، مسکن محمدی\n\n*ما قدردان اعتماد شما هستیم*\n\n✓ ارادتمند شما محمدی ✓', 'floor': '۲', 'all_floors': '۵', 'build_date': '۱۴۰۳', 'rooms': '۲', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 39, 'city': 'زنجان', 'title': 'شخصی ساز ۱۰۰m ورودی شهرک اندیشه', 'category': 'فروش آپارتمان', 'time': '۱۵ ساعت پیش در زنجان', 'meterage': '۱۰۰', 'price': '۳٬۶۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۶٬۰۰۰٬۰۰۰', 'image': '', 'description': 'با سلام\nفروش واحد شخصی ساز شهرک اندیشه\nموقعیت عالی\nفوق العاده خوش نقشه وشیک\nمتریال درجه یک\nنورگیر عالی\nسازه محکم واستاندارد\nدسترسی به امکانات رفاهی عالی\nورودی شهرک اندیشه\nکلیدجهت بازدیدموجود\nجهت اطلاعات بیشتر تماس حاصل فرمایید', 'floor': '۱', 'all_floors': '', 'build_date': '۱۴۰۳', 'rooms': '۲', 'latitude': 36.670807, 'longitude': 48.54211, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 40, 'city': 'زنجان', 'title': '*آپارتمان ۸۷متری پشت هتل پارک(میدان آزادی)', 'category': 'فروش آپارتمان', 'time': '۱۵ ساعت پیش در زنجان', 'meterage': '۸۷', 'price': '۲٬۷۹۹٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۲٬۱۷۲٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/afra/post/b36WfZEW8J74RKx_ANC9SA/9a98a99b-2056-40c8-80a3-365b6c804f16.jpg', 'description': '۸۷متر\nدوخواب\nکلا ۳طبقه ۳واحد\nفقط طبقه اول موجود میباشد\nساختمان اماده تحویل میباشد\nده درصد برای سند نگه میشود که از کل مبلغ کسر خواهد شد', 'floor': '۱', 'all_floors': '', 'build_date': '۱۴۰۲', 'rooms': '۲', 'latitude': 36.654213, 'longitude': 48.496044, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 41, 'city': 'زنجان', 'title': 'آپارتمان ۱۱۲ متری ،وحیدیه', 'category': 'فروش آپارتمان', 'time': '۱۵ ساعت پیش در زنجان', 'meterage': '۱۱۲', 'price': '۴٬۴۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۹٬۲۸۵٬۰۰۰', 'image': '', 'description': 'آپارتمان ۱۱۲ متری، وحیدیه، شریعت دوم\nاتاق خواب ها هر دو نورگیر، داکت بزرگ\nتراس خوب\nساختمان خلوت\nکامل تکمیل و مجهز، بدون ریالی هزینه\nکابینت mdf ، آسانسور، انباری بزرگ، پارکینگ درب ریموت دار، \n۴ طبقه ۴ واحد\nتخفیف پای معامله\nمشاور: محمدی، املاک عصر جدید شهرک کارمندان', 'floor': '۲', 'all_floors': '۴', 'build_date': '۱۳۹۰', 'rooms': '۲', 'latitude': 36.680813, 'longitude': 48.496468, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 42, 'city': 'زنجان', 'title': 'آپارتمان جنوبی/105متر/اعتمادیه', 'category': 'فروش آپارتمان', 'time': '۱۵ ساعت پیش در زنجان', 'meterage': '۱۰۵', 'price': '۴٬۲۵۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۴۰٬۴۷۶٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/neda/post/avw-RDxBLS_srNVq1KrNBw/eab9ba8e-d6b5-433e-8f47-cc8b6adc4a54.jpg', 'description': 'با سلام و احترام\n✔️متراژ\u200cc :105\n✔️جنس کف :سرامیک\n✔️کابینت :ام دی اف\n✔️طبقه :اول\n✔️واحد در طبقه :2\n✔️پارکینگ :دارد\n✔️انباری :دارد\n✔️آسانسور :دارد\n      n✔️موقعیت :جنوبی\n✔️توضیحات :\n4/8\n\n\n✔️فایلهای مشابه موجود است، \n✔️ خرید و فروش ملک تان را به ما بسپارید، \n✔️ جهت خرید و فر    روش ملک خود عدد 1 را ارسال نمایید تا در کوتاهترین زمان ممکن با شما تماس گرفته\xa0 میشود، \n✔️آدرس دفتر:خیابان خرمشهر،روبروی بانکک ملی،بنش خیابان سوم شعبان، املاک بهار', 'floor': '۱', 'all_floors': '۴', 'build_date': '۱۳۹۰', 'rooms': '۲', 'latitude': 36.693311043624, 'longitude': 48.549310729201, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 43, 'city': 'زنجان', 'title': 'پونک/  فروش واحدهای ۸۵و ۹۵ متری /خشک', 'category': 'فروش آپارتمان', 'time': '۱۵ ساعت پیش در زنجان', 'meterage': '۹۰', 'price': '۳٬۰۶۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۴٬۰۰۰٬۰۰۰', 'image': '', 'description': 'لوکیش عالی \nمتریال ساخت عالی \nسازنده بنام \nخوش نقشه \nشیک و دلباز \nآماده تحویل \nخشک \nقابلیت معاوضه با ملک کلنگی \nجهت مشاوره و اطلاعات بیشتر لطفا تماس بگیرید پاسخگوی چت و پیامک نیستم.\n=====================================\nمالکین محترم لطفا آدرس و نشانی ملک خود را به ما داده تا در اسرع وقت نسبت به اجاره یا فروش آن اقدام نماییم .\n=====================================\nمشاور املاک تک \nبا بیش از ۱۳ سال سابقه \nفعالیت در کلیه امور ملکی \nمشارکت در ساخت \nبا تشکر مشاورین شما \nغفاری \nطهماسبی', 'floor': '۳', 'all_floors': '۹', 'build_date': '۱۴۰۳', 'rooms': '۲', 'latitude': 36.68015, 'longitude': 48.49214, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 44, 'city': 'زنجان', 'title': 'شهرک کارمندان فاز ۳ - ۱۵۰ متر', 'category': 'فروش آپارتمان', 'time': '۱۶ ساعت پیش در زنجان', 'meterage': '۱۵۰', 'price': '۱۲٬۰۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۸۰٬۰۰۰٬۰۰۰', 'image': '', 'description': 'نوساز کلید نخورده - خشک\nسند تک برگ \nساختمان جنوبی\nطبقه ۱ رو به خیابان\n۳ خواب نورگیر\nحال و پذیرایی نورگیر\nاشپزخانه نورگیر\n⛔️فایل شخصی میی باشد⛔️\n⛔️لطفا املاک محترم تماس نگیرند⛔️\n⛔️قیمت مقطوع و به صورت نقد می باشد⛔️', 'floor': '۱', 'all_floors': '۵', 'build_date': '۱۴۰۲', 'rooms': '۳', 'latitude': 36.693311043624, 'longitude': 48.511569499969, 'elevator': '1', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''},
    {'id': 45, 'city': 'زنجان', 'title': 'مجتمع فجر معاوضه یا فروش', 'category': 'فروش آپارتمان', 'time': '۱۱ ساعت پیش در زنجان', 'meterage': '۱۱۰', 'price': '۳٬۸۰۰٬۰۰۰٬۰۰۰', 'price_per_meter': '۳۴٬۵۴۵٬۰۰۰', 'image': 'https://s100.divarcdn.com/static/photo/afra/post/boPwcvtAYJKn3U41X5tQaQ/58efee1b-dfd9-4cec-a5d3-78e0b36c9cb4.jpg', 'description': 'سلام. واحد در مجتمع فجر رو به قائم ۱ جاده شهرک، طبقه یک و نیم (۱/۵)،طبقه اول نیم طبقه دارای ۸پله. واحد دوکله شمالی جنوبی،آشپزخانه،خوابها و پذیرایی همگی نورگیر و رو به فضای سبز.بدون مشرف و رو به کوههای گاوازنگ وکاملا دلباز،دارای پارکینگ اختصاصی مسقف و درب دار.از مقابل بلوک هیچ ترددی  غیر از خود بلوک وجود نداشته ومانند حیاط اختصاصی می باشد.دارای فضای سبز زیبا با همسایگان بسیار محترم و محیط آرام و دلباز.\nبا آپارتمان همکف در همین مجتمع ویا آپارتمان آسانسوردار در مرکز شهر قابل معاوضه است.', 'floor': '۲', 'all_floors': '۴', 'build_date': '۱۳۸۵', 'rooms': '۲', 'latitude': 36.686566168377, 'longitude': 48.502539242324, 'elevator': '0', 'parking': '1', 'warehouse': '1', 'jahat': '', 'vahed': '', 'sanad': '', 'status': ''}]

for home in homes:
    mtr = utils.convert_persian_text_to_english_digits(home['meterage'])
    prc = utils.convert_persian_text_to_english_digits(home['price'])
    ppm = utils.convert_persian_text_to_english_digits(home['price_per_meter'])
    flr = utils.convert_persian_text_to_english_digits(home['floor'])
    avhd= utils.convert_persian_text_to_english_digits(home['all_floors'])
    rms = utils.convert_persian_text_to_english_digits(home['rooms'])
    elevator=utils.convert_persian_text_to_english_digits(home['elevator'])
    parking=utils.convert_persian_text_to_english_digits(home['parking'])
    warehouse =utils.convert_persian_text_to_english_digits(home['warehouse'])
    
    Building.objects.create(
        id=home['id'],
        city=home['city'],
        category=home['category'],
        title=home['title'],
        #time=home['time'],
        time = "2001-01-01", ### TODO
        meterage=mtr,
        price=prc,
        price_per_meter=ppm,
        image=home['image'],
        description=home['description'],
        floor=flr,
        all_floors=avhd,
        build_date=home['build_date'], 
        rooms=rms,
        facilities = f"[{elevator},{parking},{warehouse}]", # type: ignore
        direction=home['jahat'],
        document_type=home['sanad'],
        status=home['status'],
        latitude=home['latitude'],
        longitude=home['longitude'],
        priorities = "[1,1,1]"# TODO, shows if the building is close to: hospital, school, park
    )